---
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
