---
- hosts: all
  become: true
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        autoremove: yes
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file
    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true and reboot_required_file is defined 
